### ISSUE TITLE
ERROR: Unable to lock database: Permission denied

### ISSUE THREAD

**Issue by robov** [wodby/webgrind#1]
I tried to build your container
```

ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

**Comment by csandanov** [comment]
Yep, that's because the base image `wodby/php` changed the default user from `root` to `www-data`. I've just updated the image accordingly and the base image is now freezed. You can try `latest` or `1.5-1.1.0`
