### ISSUE TITLE
Webgrind - Impossible to generate Graph

### ISSUE THREAD

**Issue by heyyo-droid** [wodby/webgrind#4]
I was able to configure Xdebug profile with webgrind.  

But I don't succeed to generate the graph. 
I got this error:  
`Unable to generate /tmp/cachegrind.out.103.gz-10.webgrind.svg via python: /usr/bin/python and dot: /usr/bin/dot. Please update config.php.`

I suppose we are missing one package in webgrind container:  
https://github.com/jokkedk/webgrind/issues/22

![image](https://user-images.githubusercontent.com/81759607/212309565-82b9aa86-36d1-4618-939e-1241b5991fa9.png)

**Comment by csandanov** [comment]
Could you please try again with the latest image, I've added `py3-graphviz` package

**Comment by heyyo-droid** [comment]
Thanks I will

**Comment by heyyo-droid** [comment]
By using WEBGRIND_TAG=latest, the problem remains.  

![image](https://user-images.githubusercontent.com/81759607/213926729-616a77f6-e180-4f48-acbf-46f0d41ddd82.png)

I can see the `py3-graphviz`  
![image](https://user-images.githubusercontent.com/81759607/213926779-1fdaf6ee-5016-4c95-8008-f06114682edb.png)

**Comment by csandanov** [comment]
it seems the issue caused by compressed xdebug files, webgrind has added the support but no tag was released https://github.com/jokkedk/webgrind/issues/156

**Comment by csandanov** [comment]
PHP now has `PHP_XDEBUG_USE_COMPRESSION`, set it to `false` and the call graph will work. That's a workaround until they release a tag with compression support

**Comment by jomoflash** [comment]
Disabling xdebug compression helps. Using below configuration in php.ini

```
[xdebug]
xdebug.mode = profile
xdebug.start_with_request = yes
xdebug.use_compression = false
```
